### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by MrTimscampi** [jdm-contrib/justdelete.me#120]
Currently, the website is not available using HTTPS.

You should use something like Let's Encrypt to get an SSL certificate and allow encrypted view of the website.  
All the major navigators are going to be blocking non-HTTPS traffic in the near future (https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/ for example) so it makes sense to support this ASAP.

The main issue I can see is that Github Pages doesn't seem to offer certificate support for custom domains.  
Sites hosted on *.github.io require it, but custom domains don't seem to be supported.

**Comment by PyroSamurai** [comment]
You've already answered your own question. It is not possible as long as we host on github and use a custom domain. We don't have any plans to change either of these.

People also complained when we didn't use a custom domain. Hosting outside of github would lead to numerous problems, least of which is uptime. Let's encrypt doesn't even enter the arena because hosting it anywhere else would lead to a slow site in first place due to the limited amount of up speed you can get for $0. The slower speed would then be compounded by the encryption speed-cost. This is infeasible.

Also, HTTP will not be blocked by any browser that wishes to continue to have a large share of the users out there. Unlike DRM, the usage of HTTP is determined by the millions of website owners out there and not the people listed in that blog post from 2015.
