### ISSUE TITLE
WTF?!

### ISSUE THREAD

**Issue by borfast** [jdm-contrib/justdelete.me#87]
This is just a polite "fuck off" for @PyroSamurai.

You decided to try to take over the [original justdelete.me project](https://github.com/justdeleteme/justdelete.me/) because you thought it was no longer maintained. Fair enough.

But you (or maybe @tupaschoal) decided to create a new repository from scratch and copy the code, instead of forking the old one on Github, and you don't point to the old repository anywhere. This might start to rub the line between "fair enough" and "disrespectful".

But @PyroSamurai, you opened up an issue (#86) and decided to spam everyone you saw in the other repository - hundreds of people. Why? You said, and I quote, "It was the most efficient way." The most efficient way of doing what? Spamming people?

Even worse, when people complained about what you did, you deleted their comments and finally closed the thread to prevent further complaints. This goes way beyond disrespectful.

It's stupid enough to spam people in a desperate attempt to grab people's attention to your project. You're a kid and feel empowered that you're trying to take over a big project that has lots of visibility. No problem. You're young and probably don't understand how these things should work yet, I can understand that - but don't be an attention whore and don't pester people with a childish attitude like this. You're only accomplishing the exact opposite of what you intended. As in, people suggesting everyone affected [reports](https://help.github.com/articles/reporting-abuse-or-spam/) you for abuse, or that everyone affected opens a new issue here complaining about what you did.

**Comment by jens1o** [comment]
Sorry, but I need to do such an action to annoy someone:

👍 

(Yes, I know I can use reactions 😜 )

**Comment by tupaschoal** [comment]
Hello @borfast,

Let me clear some things up. We didn't think the original repo is abandoned, it is. We asked the original owner to transfer it to our ownership so we could maintain it and he said he couldn't, because he doesn't hold it anymore. It was sold to a shady organization who just placed it into a questionable domain and forgot about it. 

I didn't copy the code, I forked it, but when we found out the original one was going nowhere, we decided to detach it. There are multiple downsides of being a fork, like not showing up in searches or not having the contributions counted for the people helping us. I think this still is fair enough. I haven't changed the license and it still credits the original owner. 

As for tagging everyone, I won't dicuss,  because it was questionable. The idea was: "hey, this project you liked wasn't abandoned, we're keeping it alive here". 

I'm keeping the issue open if anyone wants to ask or discuss anything else. I apologise!

**Comment by borfast** [comment]
> We didn't think the original repo is abandoned, it is.

No one is questioning that. It does seem abandoned.

> As for tagging everyone, I won't dicuss, because it was questionable.

No, it was not questionable, it was disrespectful and a very childish attitude, and you, as the creator of this new repo, *should* discuss it. Unlocking the other thread is probably not a good idea because it will only allow more spam to get through to the affected people but perhaps unlock it, post a public apology, and lock it again. You guys as a team should publicly acknowledge the mistake and apologize there.

> The idea was: "hey, this project you liked wasn't abandoned, we're keeping it alive here".

I think everyone understood what the idea was but the approach, and especially the attitude towards complaints, was very, very wrong.

**Comment by tupaschoal** [comment]
When I said "won't discuss it" I kind of intended to say that I wouldn't come up with any excuses, but would be open to discussing it on this thread, if  you wanted, which is what we're doing.

I've opened #88 with the public apology, I don't think it is wise to spam everyone again on #86, even more because those who disliked it the most will have already unsubscribed and won't get the message anyway. 

I apologise, again.

**Comment by galeksandrp** [comment]
#86

**Comment by Nezteb** [comment]
I recommend reporting it as abuse. I did. https://github.com/contact/report-abuse
