### ISSUE TITLE
Mass Tagging Public Apology

### ISSUE THREAD

**Issue by tupaschoal** [jdm-contrib/justdelete.me#88]
We're sorry if you have been mass tagged and spammed on issue #86. As enthusiasts of the project, we wanted to let everyone know it is still alive, but we made a bad decision. Hope you understand and get the apologies, we have no excuses. 
Sorry!

**Comment by Nezteb** [comment]
I recommend reporting it as abuse. I did. https://github.com/contact/report-abuse

**Comment by lipis** [comment]
@Nezteb They already apologized quite a few times.. what else do you need?! It was a bad call, they admitted it and apologized for.. case closed. We can all go back to our normal life now..

**Comment by jomo** [comment]
Thanks for the apology. Also thank you for keeping the project alive!

Just in case anybody reading needs to make a similar decision in the future, I think the best approach is to open an issue on the original repo to discuss the projects future and point out your fork (which you [actually did](https://github.com/justdeleteme/justdelete.me/issues/731#issuecomment-289168564)). That way people watching the repo will be notified and anybody trying to figure out what's up will easily find it.

You could then also start merging PRs from the original repo, which will draw some attention to the fork as well without immediately spamming hundreds of people and subscribing them to a noisy thread.

**Comment by tupaschoal** [comment]
I thought about merging their PRs, but I'm afraid it might update the repo with outdated information. Am interested to hear what other people think, though.

**Comment by caffeinewriter** [comment]
I'd like to say I appreciate the apology. JDM is a project I've been a fan of for a while, so I do appreciate the effort to keep the project alive.

I'd also like to explain why the stargazer issue was particularly problematic for me. Since I'm not typically involved in many Github Issue chains, the emails I do get from GH Issues are typically important to me, so I do want to jump on those as quickly as possible, so they will actually result in a notification on my phone. Since once I'm mentioned in an issue, I'm automatically and forcefully subscribed, every subsequent comment does generate an email which actually notifies me. 

Again, I appreciate the apology, and just wanted to explain part of why it had some people so incensed. 

As for the existing pull requests, I think merging them would be more beneficial than waiting for new PRs. The two options I see for PRs being merged are either adding new sites that otherwise would not have been there, or updating instructions for existing sites. Either way, it would result in more current information for the site, and if it is out of date, give people a base to update the information from, particularly if a site wasn't listed on JDM beforehand.

**Comment by reportingforduty** [comment]
The original git is a mess. If it is alive, they could answer to each issues and close it. Instead they just ignored them. That's why I create many issues here(forked one), instead of creating to original one.

If the original one is back from the dead, its owner must apologize first.
